### ISSUE TITLE
Broker selection - UserApp

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#11]
-	A check mark on top right (broker) is missing when a broker is selected. Refer to the design for reference.
-	The right panel (BrokerageApplications) shall have a flexible scroll bar than fixed, meaning as and when the brokerage applications items grows the scroll bar also grows. Currently the scroll is fixed to certain height even if there are no applications.

Screen details
1) Chrome
2) 1366 X 768

![user_image_2](https://cloud.githubusercontent.com/assets/23191755/21838551/91b26642-d7f8-11e6-8cd0-7c333bc5e03f.JPG)

**Comment by abhishekgupta92** [comment]
fixed

**Comment by suneelng** [comment]
@abhishekgupta92 

- Check mark on broker selection is still missing.

screen shot
![image](https://cloud.githubusercontent.com/assets/23191755/22605687/023bbb3a-ea77-11e6-8ba8-eb96deff9f23.png)

**Comment by suneelng** [comment]
@abhishekgupta92 

- Missing check mark on the top right when a broker is selected.
- Please refer to the design.

**Comment by abhishekgupta92** [comment]
This was fixed in https://github.com/shastri9999/kyck/commit/77118e406b813b8bae6fbe8e39c60583d01295f9. Can you check if the code you are checking has this commit?

**Comment by suneelng** [comment]
Issue still not resolved,
Tested on other browsers as well.

Screen details

Chrome
1680 X 1050

![image](https://cloud.githubusercontent.com/assets/23191755/23738747/d65b837e-04c0-11e7-8811-0d297d0da3d6.png)
