### ISSUE TITLE
Approve event (brokerApp)

### ISSUE THREAD

**Issue by suneelng** [shastri9999/kyck#41]
- Approve event does not update the status in all references.
- the left section still shows pending but the summary tab shows the updated value.

Reference
![image](https://cloud.githubusercontent.com/assets/23191755/21943517/92c1ee58-d9f7-11e6-92d4-ed777c7dad42.png)

**Comment by abhishekgupta92** [comment]
Fixed. If I log in using broker1@broker.com, and approve the request by "Another One", then I can't approve the reuqest. 

Here's the server trace which comes. Note that brokerageId is null.

Resource
$promise:Promise
$resolved:true
Message:" Successful"
Status:"SUCCESS"
data:Object
brokerageId:null
status:"APPROVED"
userId:"another.kyck@mailinator.com"
__proto__:Object
__proto__:Object

**Comment by suneelng** [comment]
@abhishekgupta92 

- After approving any application, the focus is lost and it is very confusing to the user as the confirmed and rejected applications are sorted to the end. Is it possible to keep the focus to the same application.
- Contacted user Search is case sensitive can we make it case-insensitive.

**Comment by suneelng** [comment]
@abhishekgupta92 

The below is still not fixed, please check
- After approving any application, the focus is lost and it is very confusing to the user as the confirmed and rejected applications are sorted to the end. Kindly keep the focus to the same application after approve or reject action.

**Comment by suneelng** [comment]
@abhishekgupta92 

- Found another bug wrt to the approve process, the graph detials (kyc/profile/etc) will disappear with below sequence,

1) Start approval process,
2) Click accept on all the tabs
3) After the last accept, the tab jumps to application summary tab and this is where the graphs disappear.
